# Generated by Django 3.1.4 on 2020-12-18 13:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBuy',
            fields=[
                ('buyerCode', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('tel', main.models.IntegerRangeField(verbose_name='Телефон')),
                ('passportCode', models.CharField(help_text='2 буквы и 7 цифр', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Длинна = 9', regex='^.{9}$')], verbose_name='Код поспорта')),
                ('passportNumber', models.CharField(help_text='14 символов', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Длинна = 14', regex='^.{14}$')], verbose_name='Индентификационный номер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент покупатель',
                'verbose_name_plural': 'Клиенты покупатели',
            },
        ),
        migrations.CreateModel(
            name='ClientSell',
            fields=[
                ('sellerCode', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('tel', main.models.IntegerRangeField(verbose_name='Телефон')),
                ('passportCode', models.CharField(help_text='2 буквы и 7 цифр', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Длинна = 9', regex='^.{9}$')], verbose_name='Код поспорта')),
                ('passportNumber', models.CharField(help_text='14 символов', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Длинна = 14', regex='^.{14}$')], verbose_name='Индентификационный номер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент продавец',
                'verbose_name_plural': 'Клиенты продавцы',
            },
        ),
        migrations.CreateModel(
            name='DealsBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('contractCode', models.CharField(max_length=100, verbose_name='Код договора')),
                ('applicationCode', models.CharField(max_length=100, verbose_name='Код заявки')),
                ('dateOfOrder', models.DateField(verbose_name='Дата составления заказа')),
                ('dateOfOperation', models.DateField(verbose_name='Дата операции')),
                ('employee', models.CharField(max_length=50, verbose_name='Сотрудник')),
                ('buyer', models.CharField(max_length=50, verbose_name='Покупатель')),
                ('seller', models.CharField(max_length=50, verbose_name='Продавец')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('profit', models.CharField(max_length=50, verbose_name='Прибыль')),
            ],
            options={
                'verbose_name': 'Резервная копия сделки',
                'verbose_name_plural': 'Резервные копии сделок',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeeCode', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код')),
                ('FIO', models.CharField(max_length=50, verbose_name='ФИО')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
                ('dateOfEmployment', models.DateField(verbose_name='Дата найма')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('tel', main.models.IntegerRangeField(verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('applicationCode', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код заявки')),
                ('dateOfOrder', models.DateField(verbose_name='Дата составления заказа')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование объекта')),
                ('area', main.models.IntegerRangeField(verbose_name='Площадь м2')),
                ('rooms', main.models.IntegerRangeField(verbose_name='Кол-во комнат')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('price', main.models.IntegerRangeField(verbose_name='Цена')),
                ('ifSelled', models.BooleanField(default=False, verbose_name='Состояние продажи')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clientsell', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимость',
            },
        ),
        migrations.CreateModel(
            name='SelledProperty',
            fields=[
                ('contractCode', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код договора')),
                ('dateOfOperation', models.DateField(verbose_name='Дата операции')),
                ('profit', models.IntegerField(verbose_name='Прибыль')),
                ('applicationCode', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.property', verbose_name='Код заявки')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clientbuy', verbose_name='Покупатель')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employees', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Совершенная сделка',
                'verbose_name_plural': 'Совершенные сделки',
            },
        ),
    ]
