# Generated by Django 3.1.4 on 2020-12-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientbuy',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='clientsell',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='clientbuy',
            name='fio',
            field=models.CharField(default=1, max_length=50, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientsell',
            name='fio',
            field=models.CharField(default=1, max_length=50, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
