# Generated by Django 3.1.4 on 2020-12-18 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201218_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='dateOfOrder',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата составления заказа'),
        ),
        migrations.AlterField(
            model_name='selledproperty',
            name='dateOfOperation',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата операции'),
        ),
    ]
